config/routes.rb
Rails.application.routes.draw do

  get 'home', to: 'home#index', as: :home
  get 'dashboard', to: 'home#dashboard', as: :dashboard

  get 'experiments', to: 'experiments#index', as: :experiments
  get 'experiments/edit/:key', to: 'experiments#edit', as: :experiments_edit
  get 'experiments/new', to: 'experiments#new', as: :experiments_new

  get 'admin', to: 'admin#index', as: :admin
  get 'admin/users', to: 'admin#users', as: :admin_users
  get 'admin/users/new', to: 'admin#new', as: :admin_users_new
  get 'admin/users/edit/:key', to: 'admin#edit', as: :admin_users_edit
  post 'admin/users/edit/:key', to: 'admin#update', as: :admin_users_update

  devise_for :users, path: '',
             controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords', confirmations: 'confirmations', unlocks: 'unlocks' },
             path_names: { sign_in: 'login', sign_out: 'logout', password: 'password', confirmation: 'confirmation', unlock: 'unlock', registration: 'user', sign_up: 'signup', edit: 'profile' }

  devise_scope :user do
    authenticated :user do
      root to: 'home#dashboard'
      get 'user/', to: 'registrations#edit'
    end
    unauthenticated :user do
      root to: 'home#index'
      get 'user/', to: 'registrations#new'
    end

    get 'signup', to: 'registrations#new', as: :user_signup
    get 'user/login', to: 'sessions#new', as: :user_login
    get 'user/unlock', to: 'unlocks#new', as: :user_acc_unlock
    get 'user/profile', to: 'registrations#edit', as: :user_edit
    get 'password', to: 'passwords#new', as: :reset_password
    get 'password/new', to: 'passwords#new', as: :main_reset_password
    get 'password/edit', to: 'passwords#edit', as: :update_password
    get 'confirmation', to: 'confirmations#new', as: :user_acc_confirmation
  end

end

app/views/admin/_user.html.erb
<tr class='clickable-row' data-href='<%= admin_users_edit_path(user) %>'>
  <td class="table-responsive-more"><p class="hidden"><%= user.id %></p></td>
  <td><%= user.lastname %></td>
  <td><%= user.firstname %></td>
  <td><%= user.role %></td>
  <td><%= user.email %></td>
  <td><%= user.code %></td>
  <td><%= user.noshow_count %></td>
  <td><%= user.participations_count %></td>
  <td><%= user.created_at.strftime("%H:%M, %d.%m.%Y") %></td>
</tr>

app/views/admin/edit.html.erb
<div class="editable-form" data-mode="read">
  <%= form_for :user, url: admin_users_edit_path(@user), action: :update, html: {"data-editable" => 'false'}, method: :post  do |f| %>
    <input value="Hello" class="form-control"/>
    <div class="user-admin-content">
      <div class="header">
        <div class="row">
          <div class="col-md-6 md-center">
            <h4 class="title">admin admin</h4>
          </div>
          <div class="col-md-6 pull-right text-right md-center">
            <div aria-label="..." class="btn-group pull-right" role="group">
              <%= link_to 'Edit', '', :class => 'btn btn-primary btn-normal edit-button editable-form-mode-switch' %>
              <div class="btn-group">
                <button class="btn btn-default btn-normal dropdown-toggle" data-toggle="dropdown" href="#" type="button">
                  Additional functions
                  <b class="caret"></b>
                </button>
                <ul class="dropdown-menu">
                  <li><a href="/hroot-demo/admin/users/1/login_as">Login as admin admin</a></li>
                </ul>
              </div>
              <button class="btn btn-default btn-normal" data-dismiss="modal" type="button">Close</button>
            </div>
          </div>
        </div>
      </div>
      <div class="modal">
        <div class="row">
          <div class="col-md-6">
            <h4>Common data</h4>
            <table class="table">
              <thead>
              <tr>
                <td>First name</td>
                <td>admin</td>
              </tr>
              </thead>
              <tbody>
              <tr>
                <td>Last name</td>
                <td>admin</td>
              </tr>
              <tr>
                <td>Role</td>
                <td>Administrator</td>
              </tr>
              <tr>
                <td>Unique code</td>
                <td>9iwaq5</td>
              </tr>
              </tbody>
            </table>
          </div>
          <div class="col-md-6">
            <h4>Account data</h4>
            <table class="table">
              <thead>
              <tr>
                <td>Email</td>
                <td><a href="mailto:admin@example.com">admin@example.com</a></td>
              </tr>
              </thead>
              <tbody>
              <tr>
                <td>Secondary email</td>
                <td></td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <h4>Required fields</h4>
            <table class="table">
              <tbody>
              </tbody>
            </table>
          </div>
          <div class="col-md-6">
            <h4>Optional fields</h4>
            <table class="table">
              <tbody>
              </tbody>
            </table>
          </div>
        </div>
        <div class="userinfo">
        </div>
      </div>
    </div>

        <%= f.label :lastname %>
        <%= f.text_field :lastname, class: 'form-control' %>
        <%= f.submit "Save changes", class: "btn btn-primary" %>

  <% end %>
</div>

app/views/admin/index.html.erb
<h4>User Control</h4>

<p>Find me in app/views/admin/index.html.erb</p>

app/views/admin/users.html.erb
<div class="row">
  <div class='col-md-12'>
    <div class="row no-side-margin">
      <div class="float-left col-6"><h4>User Control</h4></div>
      <div class="float-right col-6 text-right">
        <div class="item-top-navi"><%= link_to 'New User', admin_users_new_path, class: 'btn btn-primary' %></div>
      </div>
    </div>
    <div class="row no-side-margin">
        <table id="experiments-table" class="display table table-striped table-bordered">
          <thead>
            <tr>
              <th class="hidden-attributes" style="width: 19px !important;"></th>
              <th scope="col">Lastname</th>
              <th scope="col">Firstname</th>
              <th scope="col">Role</th>
              <th scope="col">Email</th>
              <th scope="col">Code</th>
              <th scope="col">No-Shows</th>
              <th scope="col">Participations</th>
              <th scope="col">Created</th>
            </tr>
          </thead>
          <tbody>
          <% @users.all.each do |user| %>
            <%= render partial: "user", locals: {user: user} %>
          <% end %>
        </table>
    </div>
  </div>
</div>