config/routes.rb
Rails.application.routes.draw do

  get 'home', to: 'home#index', as: :home
  get 'dashboard', to: 'home#dashboard', as: :dashboard

  get 'experiments', to: 'experiments#index', as: :experiments
  get 'experiments/edit/:key', to: 'experiments#edit', as: :experiments_edit
  get 'experiments/new', to: 'experiments#new', as: :experiments_new

  get 'admin', to: 'admin#index', as: :admin
  get 'admin/users', to: 'admin#users', as: :admin_users
  get 'admin/users/new', to: 'admin#new', as: :admin_users_new
  get 'admin/users/edit/:key', to: 'admin#edit', as: :admin_users_edit
  post 'admin/users/edit/:key', to: 'admin#update', as: :admin_users_update

  devise_for :users, path: '',
             controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords', confirmations: 'confirmations', unlocks: 'unlocks' },
             path_names: { sign_in: 'login', sign_out: 'logout', password: 'password', confirmation: 'confirmation', unlock: 'unlock', registration: 'user', sign_up: 'signup', edit: 'profile' }

  devise_scope :user do
    authenticated :user do
      root to: 'home#dashboard'
      get 'user/', to: 'registrations#edit'
    end
    unauthenticated :user do
      root to: 'home#index'
      get 'user/', to: 'registrations#new'
    end

    get 'signup', to: 'registrations#new', as: :user_signup
    get 'user/login', to: 'sessions#new', as: :user_login
    get 'user/unlock', to: 'unlocks#new', as: :user_acc_unlock
    get 'user/profile', to: 'registrations#edit', as: :user_edit
    get 'password', to: 'passwords#new', as: :reset_password
    get 'password/new', to: 'passwords#new', as: :main_reset_password
    get 'password/edit', to: 'passwords#edit', as: :update_password
    get 'confirmation', to: 'confirmations#new', as: :user_acc_confirmation
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, :except => [:index]
  before_action :redirect_on_logged_in, :only => [:index]

  add_breadcrumb "Home", :root_path

  def index

  end

  def dashboard

  end

  private

  def redirect_on_logged_in
    redirect_to dashboard_path if current_user
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/dashboard.html.erb
<div class='row'>
  <div class='col-sm-12'>
    <div class='jumbotron'>
      <h4>Welcome <%= current_user.lastname %>!</h4><br /> <br /><br />

      <p>
        Your Properties
        <ul>
        <% if user_signed_in? %>
        <li><%= link_to 'Role: ' + current_user.role, '', class: 'nav-link' %> </li>
          <li > <%= link_to ('Moderator: ' + (current_user.moderator? ? 'yes' : 'no')), '', class: 'nav-link' %> </li>
      <% end %>
        </ul>
      </p>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class='row'>
  <div class='col-sm-9'>
    <div class='jumbotron'>

      <h1>Welcome!</h1>
      <p>Register to get started.</p>
      <p>
        <%= link_to 'Register', user_signup_path, class: 'btn btn-primary btn-lg' %>
      </p>

    </div>
  </div>
  <div class='col-sm-3 home-login'>
    <%= form_for(:user, url: session_path(:user)) do |f| %>
      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
      </div><br />

      <div class="field">
        <%= f.label :password %><br />
        <%= f.password_field :password, autocomplete: "current-password", class: "form-control" %>
      </div> <br />

        <div class="field">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %>
        </div> <br />

      <div class="actions">
        <%= f.submit "Log in", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>