config/routes.rb
Rails.application.routes.draw do

  get 'home', to: 'home#index', as: :home
  get 'dashboard', to: 'home#dashboard', as: :dashboard

  get 'experiments', to: 'experiments#index', as: :experiments
  get 'experiments/edit/:key', to: 'experiments#edit', as: :experiments_edit
  get 'experiments/new', to: 'experiments#new', as: :experiments_new

  get 'admin', to: 'admin#index', as: :admin
  get 'admin/users', to: 'admin#users', as: :admin_users
  get 'admin/users/new', to: 'admin#new', as: :admin_users_new
  get 'admin/users/edit/:key', to: 'admin#edit', as: :admin_users_edit
  post 'admin/users/edit/:key', to: 'admin#update', as: :admin_users_update

  devise_for :users, path: '',
             controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords', confirmations: 'confirmations', unlocks: 'unlocks' },
             path_names: { sign_in: 'login', sign_out: 'logout', password: 'password', confirmation: 'confirmation', unlock: 'unlock', registration: 'user', sign_up: 'signup', edit: 'profile' }

  devise_scope :user do
    authenticated :user do
      root to: 'home#dashboard'
      get 'user/', to: 'registrations#edit'
    end
    unauthenticated :user do
      root to: 'home#index'
      get 'user/', to: 'registrations#new'
    end

    get 'signup', to: 'registrations#new', as: :user_signup
    get 'user/login', to: 'sessions#new', as: :user_login
    get 'user/unlock', to: 'unlocks#new', as: :user_acc_unlock
    get 'user/profile', to: 'registrations#edit', as: :user_edit
    get 'password', to: 'passwords#new', as: :reset_password
    get 'password/new', to: 'passwords#new', as: :main_reset_password
    get 'password/edit', to: 'passwords#edit', as: :update_password
    get 'confirmation', to: 'confirmations#new', as: :user_acc_confirmation
  end

end

app/views/layouts/_footer.html.erb
<div class="container-fluid">
  <div class='row'>
    <div class='col-md-12'>
      <hr>
      © 2018 Martin Belica | <a href="/home/about">Site credits and contact</a>
      <br />  <br />
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'vpLab', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item"><%= link_to 'Dashboard', root_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Profile', user_edit_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Calendar', '#', class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Experiments', experiments_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Users Management', admin_users_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Site Settings', '#', class: 'nav-link' %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <%= link_to 'Log out', destroy_user_session_path, class: 'nav-link nav-btn', method: :delete %>
        <% else %>
          <%= link_to 'Log In', user_login_path, class: 'nav-link nav-btn' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VpLab</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://fonts.googleapis.com/css?family=Rubik" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <% if (params[:controller] != 'home') %>
      <div class="container-fluid">
        <div class="row hidden-print">
          <div class="col-sm-12">
            <ul class="breadcrumb ">

              <%= render_breadcrumbs  :tag => :li, :separator => ' / ' %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>

    <div class="container-fluid">
      <div class='row'>
        <div class='col-sm-12 flash'>
          <% flash.each do |key, value| %>
            <% if key != 'timedout' %>
              <div class="alert alert-<%= key %> .alert-dismissible">
                <%= value %>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>

      <%= yield %>

      <%= render 'layouts/footer' %>
    </div>

  </body>
</html>